mat/urls.py
from django.conf.urls import url
from mat import views

app_name = 'mat'

urlpatterns = [
    url(r'^$',views.home_page, name="home"),
    url(r'^mft/$', views.mat_mft_get_data, name="mat-get-data"),
]

os_sim/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mat/', include('mat.urls')),
]

mat/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mat/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
import json

def home_page(request):
    return render(request, 'mat/index.html')

def mat_mft_get_data(request):
    variables = ['total_memory', 'no_of_blocks']
    submitted = True
    context = {}
    block_size = [0,1,2,3,4,5,6,7,8,0,1,1,1,1,1]
    context['invalid_data'] = False
    for x in variables:
        submitted = request.POST.get(x,False)
        if submitted is False:
            print("Hello")
            break
        else:
            try:
                context[x] = int(request.POST.get(x))
            except ValueError:
                context['invalid_data'] = True
                break

    if context['invalid_data'] is False and submitted:
        for i in range(1, context['no_of_blocks']+1):
            block_size[i] = request.POST.get('block_size_' + str(i))
        context['block_size'] = json.dumps(block_size)

    if submitted is False or context['invalid_data'] is True:
        return render(request, 'mat/mft/get_data.html', context)
    else:
        return render(request, 'mat/mft/show_demo.html', context)

def mat_mvt_get_data(request):
    return

templates/mat/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
        Memory Allocation Techniques
    </title>


    <!-- CSS Additional Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <!-- JavaScript Additional Files -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div id="top-content">
        <h1 id="page-heading">
            Memory Management Techniques
        </h1>
    </div>
    <div id="middle-content">
        <h3>What do you want to see?</h3>
        <br>
        <div>

        </div>
    </div>
</div>
</body>
</html>

templates/mat/mft/get_data.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
        Memory Management
    </title>

        <!-- CSS Additional Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/mft/style.css' %}">


    <!-- JavaScript Additional Files -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/mft/main.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div id="page-heading">
        <h1>
            Multiprogramming With Fixed Number of Tasks
        </h1>
    </div>
    <div id="input-data-form">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
        <div id="input-data-heading">
            <h3>Please Enter the following data</h3>
        </div>
        {% if invalid_data == True %}
            <p style="color:red">Invalid Data</p>
        {% endif %}
        <form class="form-horizontal" action="{% url 'mat:mat-get-data' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label col-sm-4" for="total_memory_input">Total Memory: </label>
                <div class="col-sm-8">
                    <input type="number" class="form-control" name="total_memory" id="total_memory_input" placeholder="Enter Total Memory" required min="1" step="1">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4" for="no_of_blocks">No. of Blocks: </label>
                <div class="col-sm-8">
                    <input type="number" class="form-control" name="no_of_blocks" id="no_of_blocks_input" placeholder="Enter No. of Blocks" required min="1" style="1/">
                </div>
            </div>
            <div class="form-group">
                <button type="button" value="Next" id="next-button" class="btn btn-default">Next</button>
            </div>
            <div id="part-2"></div>
            <div class="form-group">
                <input id="submit-button" type="submit" value="Submit" class="btn btn-info">
            </div>
        </form>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>
</body>
</html>

templates/mat/mft/show_demo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
        Memory Management
    </title>

        <!-- CSS Additional Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/mft/style.css' %}">


    <!-- JavaScript Additional Files -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/mft/demo.js' %}"></script>
    <script src="{% static 'js/typeit.js' %}"></script>
</head>
<script>
    var totalMemory = {{ total_memory }};
    var noOfBlocks = {{ no_of_blocks }};
    var blockSize = {{ block_size|safe }};
    console.log(blockSize[1]);
</script>
<body>
<div class="container-fluid">
    <div id="page-heading">
        <h1>Memory Allocation Techniques</h1>
    </div>
    <div id="selection-form">
        <button type="button" id="first-fit-select" class="btn btn-default">First-Fit</button>
        <button type="button" id="best-fit-select" class="btn btn-default">Best-Fit</button>
        <button type="button" id="worst-fit-select" class="btn btn-default">Worst-Fit</button>
    </div>
    <div id="demo-box">
        <div class="col-sm-6" id="left-box">
            <div class="col-sm-6">
                <h4>Main Memory</h4>
                <div id="memory-box">

                </div>
            </div>
            <div class="col-sm-6">
                <h4>Input Queue</h4>
                <div id="input-q-box">

                </div>
                <button class="btn btn-info" id="add-process-button">Add Process</button>
            </div>
        </div>
        <div class="col-sm-6" id="right-box">
            <div class="row" id="top-box">
                <h3>Output Table</h3>
                <table class="table table-striped" id="output-table">
                    <thead>
                    <tr>
                        <th>Process No.</th>
                        <th>Process Size</th>
                        <th>Allocation Status</th>
                        <th>Block No.</th>
                        <th>Internal Fragmentation</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <div class="row" id="bottom-box">
                <div id="terminal-header" style="text-align: center;">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6">Terminal - log.txt</div>
                    <div class="col-sm-3"></div>
                </div>
                <div id="terminal-body">

                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>